id: d6_private_content_settings
label: Private content settings
migration_tags:
  - Drupal 6
source:
  plugin: d6_private_content_settings
destination:
  plugin: d6_private_content_settings
migration_dependencies:
  required:
    - d6_node_type
